fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file]
      - id: clang-tidy
        args: [--config-file=./.clang-tidy]
      - id: cppcheck
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.34.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]