fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file]
      - id: clang-tidy
      - id: cppcheck
        args: [--suppress=passedByValue,--suppress=unusedStructMember,--suppress=unmatchedSuppression,--suppress=missingIncludeSystem,--suppress=unusedFunction,--suppress=noConstructor]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.34.0
    hooks:
      - id: commitizen
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=175']   # Obviously modify this if you really need to check-in a very large file
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^docs/(html|latex)
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=no']
      - id: trailing-whitespace
        exclude: ^docs/(html|latex)
