#!/usr/bin/env bash

if git rev-parse --verify HEAD >/dev/null 2>&1
then
against=HEAD
else
# Initial commit: diff against an empty tree object
against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Test clang-format
clangformatout=$(git clang-format --diff --staged -q)

# Redirect output to stderr.
exec 1>&2

if [ "$clangformatout" != "" ]
then
    echo "Format error!"
    echo "Use git clang-format"
    echo "Note: If you really think the results are completely wrong, you might want to edit the .clang-format file at the top of the repository"
    echo "Alternatively, you might want to insert '// clang-format off' and '// clang-format on' markers before and after the offending code, but this should practically never occur"
    exit 1
fi
