name: MacOS Compile CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - name: Run CMake
      uses: lukka/run-cmake@v10
