name: Ubuntu Compile and Lint CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - name: update apt-get
      run: sudo apt-get update
    - name: install pre-requisites
      run: sudo apt-get install cppcheck
    - name: configure
      run: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - name: build
      run: cmake --build build --parallel $(nproc)
    - name: pre-lint
      run: mv ./build/compile_commands.json ./compile_commands.json
    - name: lint
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files
