name: Ubuntu Compile and Lint CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: lukka/get-cmake@latest
    - name: Restore artifacts, or setup vcpkg (does not install any package)
      uses: lukka/run-vcpkg@v10
    - name: Setup apt-get for installing SFML dependencies
      run: sudo apt-get update
    - name: Install SFML dependencies via apt-get # (yes even vcpkg's version needs those)
      run: sudo apt-get install libx11-dev libxrandr-dev libxi-dev libudev-dev libgl1-mesa-dev
    - name: Run CMake consuming vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@v10
      with:
          configurePreset: 'use-vcpkg'
    - name: Build
      run: cmake --build . --parallel $(nproc)
    - name: Install linting pre-requisites
      run: sudo apt-get install cppcheck
    - name: Lint
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files
