name: Ubuntu Compile and Lint CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: lukka/get-cmake@latest
    - name: Restore artifacts, or setup vcpkg (does not install any package)
      uses: lukka/run-vcpkg@v10
    - name: Run CMake consuming vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@v10
      with:
          configurePreset: ''
    - name: Install linting pre-requisites
      run: sudo apt-get install cppcheck
    - name: Prepare compile_commands.json for linting
      run: mv ./build/compile_commands.json ./compile_commands.json
    - name: Lint
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files
