name: Windows Compile CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: lukka/get-cmake@latest
    - name: Restore artifacts, or setup vcpkg (does not install any package)
      uses: lukka/run-vcpkg@v10
    - name: Run CMake consuming vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@v10
      with:
          configurePreset: 'vcpkg'
    - name: Build
      run: cmake --build . --parallel $(nproc)
    - name: Test
      run: cmake --build . --target RUN_TESTS
